#!/bin/bash
if [[ "$1" == '--version' ]]; then
  exec /opt/google/chrome/chrome "$@"
else
  exec 1>/proc/1/fd/1
  exec 2>/proc/1/fd/2

  #args=()
  #while [[ "$#" -ne 0 ]]; do
  #  if [[ "$1" == --user-data-dir=* ]]; then
  #      dir=${1#*=}
  #      echo "Changing ownership for $dir to chrome"
  #      mkdir -p "$dir/Default"
  #      chown -R chrome:chrome "$dir"
  #  fi
  #  args+=("$1")
  #  shift
  #done
  # Use "${args[@]}" instead of "$@"

  exec chpst -u chrome:chrome env HOME=/home/chrome google-chrome --headless --disable-gpu "$@"
  #exec /opt/google/chrome/chrome --headless --disable-gpu --no-sandbox "$@"
fi

